#!/bin/bash

delimiter=","
num_lines="5"
zero_indexing="1"

while [[ $# -gt 1 ]]; do
	if [[ $1 == -d* ]]; then
		delimiter=${1:2}
	elif [[ $1 == -n* ]]; then
		num_lines=${1:2}
	elif [[ $1 == -i* ]]; then
		zero_indexing=${1:2}
	fi
	shift
done

path=$1
header=$(head -n 1 ${path})
if [[ ${zero_indexing} == 0 ]]; then 
	count=0
	string="0"
else
	count=1
	string="1"
fi

for ((i = 0; i < ${#header}; i++)); do
    if [[ "${header:$i:1}" == "$delimiter" ]]; then
        ((count++))
	string+="${delimiter}${count}"
    fi
done

(echo ${string}; head -n ${num_lines} ${path}) | column -t -s${delimiter} | less -S

